services:
  patched:
    build:
      context: ./app
      args:
        DEBUG: 'true'
        PORT: 8000
        ENV_NAME: 'patched'
    ports:
      - "8000:8000"
    cpuset: "1"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
  v2_2_3:
    build: 
      context: ./app
      args:
        DEBUG: 'true'
        PORT: 5000
        ENV_NAME: 'original'
    ports:
      - "5000:5000"
    cpuset: "1"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
  v2_3_8:
    build:
      context: ./app
      args:
        DEBUG: 'true'
        PORT: 9008
        ENV_NAME: 'v2_3_8'
    ports:
      - "9008:9008"
    cpuset: "1"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
  v2_3_7:
    build:
      context: ./app
      args:
        DEBUG: 'true'
        PORT: 9007
        ENV_NAME: 'v2_3_7'
    ports:
      - "9007:9007"
    cpuset: "1"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M